2022-05-30 08:46:12,268 INFO     Sending notify_new_login email to ['Desdemona <desdemona@zulip.com>']
2022-05-30 09:51:31,523 INFO     Sending followup_day1 email to ['user-23 <user-23@zulip.com>']
2022-05-30 09:51:31,634 INFO     Sending followup_day2 email to ['user-23 <user-23@zulip.com>']
2022-05-30 09:59:10,380 INFO     Sending notify_new_login email to ['user-23 <user-23@zulip.com>']
2022-05-30 10:02:01,495 INFO     Sending notify_new_login email to ['Desdemona <desdemona@zulip.com>']
2022-05-30 10:12:19,625 INFO     Sending confirm_registration email to ['deepak@webnyxa.tech'] in zulip (triggered from 127.0.0.1)
2022-05-30 10:12:59,598 INFO     Sending followup_day1 email to ['deepak <deepak@webnyxa.tech>']
2022-05-30 10:12:59,703 INFO     Sending followup_day2 email to ['deepak <deepak@webnyxa.tech>']
2022-05-30 10:19:40,803 INFO     Sending notify_new_login email to ['Desdemona <desdemona@zulip.com>']
2022-05-30 10:21:05,676 INFO     Sending confirm_new_email email to ['bablu.kumar@webnyxa.tech'] in zulip
2022-05-30 10:21:36,507 INFO     Sending notify_change_in_email email to ['desdemona@zulip.com'] in zulip
2022-05-31 07:48:53,034 INFO     Sending confirm_registration email to ['bkmr4228@gmail.com'] in zulip (triggered from 127.0.0.1)
2022-05-31 07:57:43,192 INFO     Sending followup_day1 email to ['kumar <bkmr4228@gmail.com>']
2022-05-31 07:57:43,456 ERROR    Error sending followup_day1 email to ['bablu.kumar@webnyxa.tech']: please run connect() first
Traceback (most recent call last):
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 274, in send_email
    if connection.send_messages([mail]) == 0:
  File "/home/chris23/zulip/zproject/email_backends.py", line 89, in send_messages
    num_sent = super().send_messages(email_messages)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.8/smtplib.py", line 865, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
Stack (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 176, in handle
    self.handle_one_request()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 201, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/chris23/zulip/zerver/middleware.py", line 304, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_scim/middleware.py", line 29, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_otp/middleware.py", line 32, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/two_factor/middleware/threadlocals.py", line 19, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chris23/zulip/zerver/decorator.py", line 131, in wrapper
    return func(request, *args, **kwargs)
  File "/home/chris23/zulip/zerver/lib/request.py", line 449, in _wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/chris23/zulip/zerver/views/registration.py", line 440, in accounts_register
    user_profile = do_create_user(
  File "/home/chris23/zulip/zerver/lib/actions.py", line 751, in do_create_user
    process_new_human_user(
  File "/home/chris23/zulip/zerver/lib/actions.py", line 541, in process_new_human_user
    enqueue_welcome_emails(user_profile, realm_creation)
  File "/home/chris23/zulip/zerver/lib/email_notifications.py", line 720, in enqueue_welcome_emails
    send_future_email(
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 355, in send_future_email
    send_email(
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 288, in send_email
    logger.exception(
2022-05-31 09:24:03,780 INFO     Sending confirm_registration email to ['babluartist057@gmail.com'] in zulip (triggered from 127.0.0.1)
2022-05-31 09:24:04,313 ERROR    Error sending confirm_registration email to ['bablu.kumar@webnyxa.tech']: SMTP AUTH extension not supported by server.
Traceback (most recent call last):
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 274, in send_email
    if connection.send_messages([mail]) == 0:
  File "/home/chris23/zulip/zproject/email_backends.py", line 89, in send_messages
    num_sent = super().send_messages(email_messages)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 709, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
Stack (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 176, in handle
    self.handle_one_request()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 201, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/chris23/zulip/zerver/middleware.py", line 304, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_scim/middleware.py", line 29, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_otp/middleware.py", line 32, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/two_factor/middleware/threadlocals.py", line 19, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chris23/zulip/zerver/views/registration.py", line 743, in accounts_home_from_multiuse_invite
    return accounts_home(
  File "/home/chris23/zulip/zerver/views/registration.py", line 713, in accounts_home
    send_confirm_registration_email(email, activation_url, request=request, realm=realm)
  File "/home/chris23/zulip/zerver/views/registration.py", line 571, in send_confirm_registration_email
    send_email(
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 288, in send_email
    logger.exception(
2022-05-31 09:32:51,236 INFO     Sending confirm_registration email to ['babluartist057@gmail.com'] in zulip (triggered from 127.0.0.1)
2022-05-31 09:32:51,773 ERROR    Error sending confirm_registration email to ['bablu.kumar@webnyxa.tech']: SMTP AUTH extension not supported by server.
Traceback (most recent call last):
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 274, in send_email
    if connection.send_messages([mail]) == 0:
  File "/home/chris23/zulip/zproject/email_backends.py", line 89, in send_messages
    num_sent = super().send_messages(email_messages)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 709, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
Stack (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 176, in handle
    self.handle_one_request()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 201, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/chris23/zulip/zerver/middleware.py", line 304, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_scim/middleware.py", line 29, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_otp/middleware.py", line 32, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/two_factor/middleware/threadlocals.py", line 19, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chris23/zulip/zerver/views/registration.py", line 743, in accounts_home_from_multiuse_invite
    return accounts_home(
  File "/home/chris23/zulip/zerver/views/registration.py", line 713, in accounts_home
    send_confirm_registration_email(email, activation_url, request=request, realm=realm)
  File "/home/chris23/zulip/zerver/views/registration.py", line 571, in send_confirm_registration_email
    send_email(
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 288, in send_email
    logger.exception(
2022-05-31 09:38:14,168 INFO     Sending confirm_registration email to ['babluartist057@gmail.com'] in zulip (triggered from 127.0.0.1)
2022-05-31 09:40:13,541 INFO     Sending followup_day1 email to ['Artist <babluartist057@gmail.com>']
2022-05-31 09:40:14,091 ERROR    Error sending followup_day1 email to ['babluartist057@gmail.com']: SMTP AUTH extension not supported by server.
Traceback (most recent call last):
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 274, in send_email
    if connection.send_messages([mail]) == 0:
  File "/home/chris23/zulip/zproject/email_backends.py", line 89, in send_messages
    num_sent = super().send_messages(email_messages)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 709, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
Stack (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 176, in handle
    self.handle_one_request()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 201, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/chris23/zulip/zerver/middleware.py", line 304, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_scim/middleware.py", line 29, in __call__
    response = self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django_otp/middleware.py", line 32, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/two_factor/middleware/threadlocals.py", line 19, in __call__
    return self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chris23/zulip/zerver/decorator.py", line 131, in wrapper
    return func(request, *args, **kwargs)
  File "/home/chris23/zulip/zerver/lib/request.py", line 449, in _wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/chris23/zulip/zerver/views/registration.py", line 440, in accounts_register
    user_profile = do_create_user(
  File "/home/chris23/zulip/zerver/lib/actions.py", line 751, in do_create_user
    process_new_human_user(
  File "/home/chris23/zulip/zerver/lib/actions.py", line 541, in process_new_human_user
    enqueue_welcome_emails(user_profile, realm_creation)
  File "/home/chris23/zulip/zerver/lib/email_notifications.py", line 720, in enqueue_welcome_emails
    send_future_email(
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 355, in send_future_email
    send_email(
  File "/home/chris23/zulip/zerver/lib/send_email.py", line 288, in send_email
    logger.exception(
2022-06-01 05:29:07,482 INFO     Sending password_reset email to ['bablu <bablu.kumar@webnyxa.tech>'] in zulip (triggered from 127.0.0.1)
2022-06-01 11:05:20,174 INFO     Sending password_reset email to ['bablu <bablu.kumar@webnyxa.tech>'] in zulip (triggered from 127.0.0.1)
2022-06-01 11:06:47,436 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
2022-06-02 05:35:19,116 INFO     Sending missed_message email to ['Artist <babluartist057@gmail.com>']
2022-06-02 05:49:48,734 INFO     Sending missed_message email to ['Artist <babluartist057@gmail.com>']
2022-06-02 12:12:56,967 INFO     Sending confirm_registration email to ['webnyxa@123.com'] in zulip (triggered from 127.0.0.1)
2022-06-02 12:13:00,708 INFO     Sending confirm_registration email to ['webnyxa@123.com'] in zulip (triggered from 127.0.0.1)
2022-06-02 12:14:16,324 INFO     Sending followup_day1 email to ['webnyxa <webnyxa@123.com>']
2022-06-02 12:14:19,678 INFO     Sending followup_day2 email to ['webnyxa <webnyxa@123.com>']
2022-06-02 12:27:04,222 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
2022-06-02 12:44:29,852 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
2022-06-02 14:05:27,651 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
2022-06-06 06:14:17,696 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
2022-06-08 07:27:17,198 INFO     Sending confirm_registration email to ['bkmr4228@gmail.com'] in zulip (triggered from 127.0.0.1)
2022-06-08 07:39:38,182 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
2022-06-08 07:44:00,577 INFO     Sending notify_new_login email to ['bablu <bablu.kumar@webnyxa.tech>']
